[package]
name = "dock_rs"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
panic = "abort"
debug = 2
lto = true
opt-level = "z"

[dependencies]
enum-map = "2.7.3"
freertos-rust = "0.2.0"
libm = "0.2.16"
log = "0.4.29"
static_cell = "2.1.1"
